#! /usr/bin/env python
import rospy
from ppt_3d.msg import Cavities
import tf
import sys
import numpy as np
import rospkg

cov_minor_min = 3e-5

data = []

def callback(msg,args):
    for cavity in msg.cavities:
        if cavity.cov_minor > cov_minor_min:
            data.append([cavity.cov_minor, cavity.cov_major])
            print ("length of data = " + str(len(data)))
            np.save(rospkg.RosPack().get_path('ppt_3d') + '/scripts/covariance_data/data/'+args[0]+".npy", np.array(data))
    
if __name__ == '__main__':
    if (len(sys.argv) == 2):
        filename = sys.argv[1]
        rospy.init_node('ppt_train_record_data')

        rospy.Subscriber("cavities", Cavities, callback, [filename])
        rospy.spin()    
